compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableInlineBuilds: true

enableTelemetry: false

nodeLinker: node-modules

preferInteractive: true

supportedArchitectures:
  cpu:
    - x86
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.1.1.cjs
